#!/bin/bash

decode_vc() {
  local jwt="$1"
  python3 -c "
import base64, json, sys
payload = '${jwt}'.split('.')[1]
payload += '=' * (4 - len(payload) % 4)
print(json.dumps(json.loads(base64.urlsafe_b64decode(payload)), indent=2))
"
}