#
# helm upgrade --kube-context=rancher-desktop --install nessus-services ./helm -f ./helm/values-services-dev.yaml
#
environment: dev

deployments:

  # Backdoor for PV access
  #
  busybox:
    pullPolicy: IfNotPresent

  # SQL Service
  #
  postgres:
    version: 17.4
    nodePort: 30543

  # Keycloak Service
  #
  keycloak:
    imagePrefix: "quay.io/keycloak/"
    image: "keycloak"
    version: nightly
    nodePort: 30800
    pullPolicy: IfNotPresent

  # Ticket Service
  #
  ticket:
    image: "nessus/oid4vc-demo-ticket"
    version: "1.0.0-SNAPSHOT"
    nodePort: 30100
    pullPolicy: IfNotPresent

  # Checkin Service
  #
  checkin:
    image: "nessus/oid4vc-demo-checkin"
    version: "1.0.0-SNAPSHOT"
    nodePort: 30200
    pullPolicy: IfNotPresent
